---
javascripts:
- base:
  - prototype
  - effects
  - dragdrop
  - controls
  - application
- facebook:
  - facebooker
stylesheets:
- base:
  - compiled/application
  - compiled/screen
- print:
  - compiled/print
- ie:
  - compiled/ie
